/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

public class App {
    public String MyNewOverCoolFeature() {
        return "Слава Україні! Героям слава!";
    }

    public static void main(String[] args) {
        System.out.println(new App().MyNewOverCoolFeature());
    }
}